export default [
  {
    is_private: false,
    zip: "77571",
    city: "Morgans Point",
    region_id: 2596,
    name: "Grimes Park Renovation",
    id: 277085,
    state: "Texas",
    bid_due_date: "2022-11-29T19:00:00Z",
    subcon_ids: [48],
    territory_id: 155,
    status: "GC and Sub Bidding",
    score: 0,
    distance: 237,
    is_unlocked: false,
    is_saved: true,
  },
  {
    is_private: false,
    zip: "75088",
    city: "Rowlett",
    region_id: 2492,
    name: "Chick-fil-A - Rowlett, TX",
    id: 276509,
    state: "Texas",
    bid_due_date: "2022-11-18T16:00:00Z",
    subcon_ids: [19],
    territory_id: 88,
    status: "GC and Sub Bidding",
    score: 0,
    distance: 7,
    is_unlocked: true,
    is_saved: false,
  },
  {
    is_private: false,
    zip: "76048",
    city: "Granbury",
    region_id: 2541,
    name: "Granbury Regional Airport Terminal Building",
    id: 276634,
    state: "Texas",
    bid_due_date: "2022-11-10T20:00:00Z",
    subcon_ids: [45],
    territory_id: 72,
    status: "GC and Sub Bidding",
    score: 0,
    distance: 72,
    is_unlocked: true,
    is_saved: false,
  },
  {
    is_private: false,
    zip: "77048",
    city: "Houston",
    region_id: 2596,
    name: "Orem Circle",
    id: 275450,
    state: "Texas",
    bid_due_date: "2022-11-03T19:00:00Z",
    subcon_ids: [58, 62],
    territory_id: 155,
    status: "GC and Sub Bidding",
    score: 0,
    distance: 233,
    is_unlocked: false,
    is_saved: false,
  },
  {
    is_private: false,
    zip: "75137",
    city: "Duncanville",
    region_id: 2492,
    name: "Chick-fil-A - Duncanville, TX",
    id: 276410,
    state: "Texas",
    bid_due_date: "2022-11-03T15:00:00Z",
    subcon_ids: [19],
    territory_id: 88,
    status: "GC and Sub Bidding",
    score: 0,
    distance: 20,
    is_unlocked: true,
    is_saved: false,
  },
  {
    is_private: false,
    zip: "77835",
    city: "Burton",
    region_id: 2574,
    name: "Burton ISD - Bond Program Campus Improvements - Burton, TX",
    id: 276190,
    state: "Texas",
    bid_due_date: "2022-11-02T18:00:00Z",
    subcon_ids: [40],
    territory_id: 76,
    status: "GC and Sub Bidding",
    score: 0,
    distance: 182,
    is_unlocked: true,
    is_saved: false,
  },
  {
    is_private: false,
    zip: "75215",
    city: "Dallas",
    region_id: 2492,
    name: "Southside Rooftop Sound Studio Pre-Solicitation",
    id: 276117,
    state: "Texas",
    bid_due_date: "2022-11-01T19:00:00Z",
    subcon_ids: [15],
    territory_id: 88,
    status: "Budgeting/Planning",
    score: 0,
    distance: 8,
    is_unlocked: true,
    is_saved: false,
  },
  {
    is_private: false,
    zip: "78132",
    city: "New Braunfels",
    region_id: 2637,
    name: "Trinity Membrane TP and Pump Station Improvements",
    id: 276416,
    state: "Texas",
    bid_due_date: "2022-11-01T19:00:00Z",
    subcon_ids: [45],
    territory_id: 348,
    status: "GC and Sub Bidding",
    score: 0,
    distance: 230,
    is_unlocked: false,
    is_saved: false,
  },
  {
    is_private: false,
    zip: "75243",
    city: "Dallas",
    region_id: 2492,
    name: "The Highlands - Guest Care Center, LLC",
    id: 276580,
    state: "Texas",
    bid_due_date: "2022-11-01T14:00:00Z",
    subcon_ids: [2],
    territory_id: 88,
    status: "GC and Sub Bidding",
    score: 0,
    distance: 8,
    is_unlocked: true,
    is_saved: false,
  },
  {
    is_private: false,
    zip: "78550",
    city: "Harlingen",
    region_id: 2653,
    name: "7-Eleven - Harlingen, TX",
    id: 276748,
    state: "Texas",
    bid_due_date: "2022-10-31T19:00:00Z",
    subcon_ids: [64],
    territory_id: 44,
    status: "GC and Sub Bidding",
    score: 0,
    distance: 461,
    is_unlocked: false,
    is_saved: false,
  },
];
